# Generated by Django 4.2.26 on 2025-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(choices=[('ntpu', '北大'), ('tnua', '台藝大'), ('chihlee', '致理科大'), ('yadong', '亞東')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '邀約中'), ('declined', '拒絕'), ('accepted', '可以來')], default='pending', max_length=20)),
                ('sheet_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'school')},
            },
        ),
    ]
