# Generated by Django 4.2.26 on 2025-11-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='school',
            field=models.CharField(choices=[('ntpu', '國立台北大學'), ('chihlee', '致理科技大學'), ('yadong', '亞東科技大學'), ('tnua', '國立台灣藝術大學')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='status',
            field=models.CharField(choices=[('pending', '邀約中'), ('invited', '已邀約'), ('declined', '拒絕'), ('accepted', '可以來')], default='pending', max_length=20),
        ),
    ]
