# Generated by Django 4.2.26 on 2025-11-16 10:37

from django.db import migrations, models
import django.db.models.deletion

DEFAULT_SCHOOLS = [
    ("ntpu", "國立台北大學"),
    ("chihlee", "致理科技大學"),
    ("yadong", "亞東科技大學"),
    ("tnua", "國立台灣藝術大學"),
]


def forwards(apps, schema_editor):
    School = apps.get_model("invites", "School")
    Invitee = apps.get_model("invites", "Invitee")
    db_alias = schema_editor.connection.alias

    slug_to_school_id = {}
    for slug, name in DEFAULT_SCHOOLS:
        school, _ = School.objects.using(db_alias).get_or_create(
            slug=slug, defaults={"name": name}
        )
        slug_to_school_id[slug] = school.id

    for invitee in Invitee.objects.using(db_alias).all():
        legacy_slug = getattr(invitee, "school_old", "")
        if not legacy_slug:
            continue
        school_id = slug_to_school_id.get(legacy_slug)
        if not school_id:
            school = School.objects.using(db_alias).create(
                slug=legacy_slug, name=legacy_slug
            )
            school_id = school.id
            slug_to_school_id[legacy_slug] = school_id
        invitee.school_id = school_id
        invitee.save(update_fields=["school"])


def backwards(apps, schema_editor):
    School = apps.get_model("invites", "School")
    Invitee = apps.get_model("invites", "Invitee")
    db_alias = schema_editor.connection.alias

    for invitee in Invitee.objects.using(db_alias).select_related("school"):
        school = invitee.school
        invitee.school_old = school.slug if school else ""
        invitee.save(update_fields=["school_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("invites", "0002_alter_invitee_school_alter_invitee_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="invitee",
            old_name="school",
            new_name="school_old",
        ),
        migrations.AddField(
            model_name="invitee",
            name="school",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitees",
                to="invites.school",
            ),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterUniqueTogether(
            name="invitee",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="invitee",
            name="school_old",
        ),
        migrations.AlterField(
            model_name="invitee",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitees",
                to="invites.school",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitee",
            unique_together={("name", "school")},
        ),
    ]
