# Generated by Django 4.2.26 on 2025-11-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0003_dynamic_school_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='status',
            field=models.CharField(choices=[('pending', '邀約中'), ('invited', '已邀約'), ('declined', '拒絕'), ('accepted', '會去')], default='pending', max_length=20),
        ),
    ]
